### ISSUE TITLE
AttributeError: mode

### ISSUE THREAD

**Issue by RadhamaniPgowda** [sveitser/kaggle_diabetic#15]
ubuntu@ip-172-31-33-63:~/kellogs/kaggle_diabetic$ python train_nn.py --cnf configs/c_128_5x5_32.py
failed to load CUDNN backend
failed to load CUDAConvNet backend
using CPU backend
{'aug_params': {'allow_stretch': True,
                'do_flip': True,
                'rotation_range': (0, 360),
                'shear_range': (0, 0),
                'translation_range': (-40, 40),
                'zoom_range': (0.8695652173913044, 1.15)},
 'balance_ratio': 0.975,
 'balance_weights': array([  1.36094537,  14.3782235 ,   6.63756614,  40.23596793,  49.61299435]),
 'batch_size_test': 128,
 'batch_size_train': 128,
 'final_balance_weights': array([ 1.,  2.,  2.,  2.,  2.]),
 'h': 112,
 'name': 'c_128_5x5_32',
 'schedule': {0: 0.003, 150: 0.0003, 201: 'stop'},
 'sigma': 0.5,
 'test_dir': 'data/test_tiny',
 'train_dir': 'data/train_tiny',
 'w': 112,
 'weight_decay': 0.0005}
Traceback (most recent call last):
  File "train_nn.py", line 40, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "train_nn.py", line 31, in main
    net.load_params_from(weights_from)
  File "/home/ubuntu/kellogs/kaggle_diabetic/src/nolearn-master/nolearn/lasagne/base.py", line 487, in load_params_from
    self.initialize()
  File "/home/ubuntu/kellogs/kaggle_diabetic/nn.py", line 131, in initialize
    out = self._output_layer = self.initialize_layers()
  File "/home/ubuntu/kellogs/kaggle_diabetic/src/nolearn-master/nolearn/lasagne/base.py", line 265, in initialize_layers
    layer = layer_factory(**layer_kw)
  File "/home/ubuntu/kellogs/kaggle_diabetic/layers.py", line 81, in __init__
    del self.mode
AttributeError: mode

How to resolve this error?

**Comment by yukkai** [comment]
I have met this problem too! did you fixed it now?

**Comment by nachimedali** [comment]
I faced the same problem, but was able to solve it by running an up to date to Theano with : 
pip install -r https://raw.githubusercontent.com/Lasagne/Lasagne/master/requirements.txt

**Comment by Raisenj** [comment]
That did not work in my case. Anybody else have faced this problem and solved?

**Comment by nszceta** [comment]
Look at the error. "using CPU backend"
You must not use the CPU backend because the codebase explicitly relies on cuDNN.

**Comment by MJ-Singh** [comment]
I have also met this problem and got the same error. Could you please specify the version of cuDNN and Cuda.

**Comment by mariliarosa4** [comment]
Did someone fixed it?

**Comment by Iammuratc** [comment]
Did any of you guys fix this problem?
