### ISSUE TITLE
Objective class in lasagne.objectives is deprecated and is removed

### ISSUE THREAD

**Issue by alishakiba** [sveitser/kaggle_diabetic#2]
Hi there,

Unfortunately, the code does not run! The error is caused by the line 7 of `nn.py` file for (this reason)[https://github.com/Lasagne/Lasagne/commit/904ae297da863a7864c6c244a1cc01b70aad9753]. I have used to `from nolearn.lasagne import objective` and then do a trick of `Objective = objective`. Although this helps in getting rid of these errors, but I encounter another error on the first line of `get_objective` method in `nn.py` file.

```
 TypeError: Error when calling the metaclass bases
 function() argument 1 must be code, not str
```

I cannot fix it yet. Would you mind publish a patch for your code! or help me to run it.

**Comment by sveitser** [comment]
It should work if you install the commits of nolearn and lasagne that are specified in the `requirements.txt` file as described in the readme. I suggest setting up a clean python virtual environment and installing the dependencies by running `pip install -r requirements.txt`.

**Comment by alishakiba** [comment]
Thanks for the reply. Although I have made a clear installation of Python 2.7 and installing all the requirements in a virtual environment, especially the versions, I cannot run the code! There is an error on line `81` of `layers.py` as `AttributeError: mode`

```
$ python train_nn.py --cnf configs/c_128_5x5_32.py
failed to load CUDNN backend
failed to load CUDAConvNet backend
using CPU backend
{'aug_params': {'allow_stretch': True,
                'do_flip': True,
                'rotation_range': (0, 360),
                'shear_range': (0, 0),
                'translation_range': (-40, 40),
                'zoom_range': (0.8695652173913044, 1.15)},
 'balance_ratio': 0.975,
 'balance_weights': array([  1.36094537,  14.3782235 ,   6.63756614,  40.23596793,  49.61299435]),
 'batch_size_test': 128,
 'batch_size_train': 128,
 'final_balance_weights': array([ 1.,  2.,  2.,  2.,  2.]),
 'h': 112,
 'name': 'c_128_5x5_32',
 'schedule': {0: 0.003, 150: 0.0003, 201: 'stop'},
 'sigma': 0.5,
 'test_dir': 'data/test_tiny',
 'train_dir': 'data/train_tiny',
 'w': 112,
 'weight_decay': 0.0005}
Traceback (most recent call last):
  File "train_nn.py", line 40, in <module>
    main()
  File "/home/ali/DiabeticRethinopathy/diabeticrethinopathy/dr2/local/lib/python2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/home/ali/DiabeticRethinopathy/diabeticrethinopathy/dr2/local/lib/python2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/home/ali/DiabeticRethinopathy/diabeticrethinopathy/dr2/local/lib/python2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ali/DiabeticRethinopathy/diabeticrethinopathy/dr2/local/lib/python2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "train_nn.py", line 31, in main
    net.load_params_from(weights_from)
  File "/home/ali/DiabeticRethinopathy/diabeticrethinopathy/dr2/src/nolearn-master/nolearn/lasagne/base.py", line 487, in load_params_from
    self.initialize()
  File "/home/ali/DiabeticRethinopathy/packages/kaggle_diabetic-master/nn.py", line 131, in initialize
    out = self._output_layer = self.initialize_layers()
  File "/home/ali/DiabeticRethinopathy/diabeticrethinopathy/dr2/src/nolearn-master/nolearn/lasagne/base.py", line 265, in initialize_layers
    layer = layer_factory(**layer_kw)
  File "/home/ali/DiabeticRethinopathy/packages/kaggle_diabetic-master/layers.py", line 81, in __init__
    del self.mode
AttributeError: mode
```

**Comment by sveitser** [comment]
Yes it would currently require a NVIDIA GPU to run as mentioned in the readme. I'll see if I can make it run on the CPU, but note that it won't be possible to train the networks within any reasonable time frame.

**Comment by sveitser** [comment]
This is now #3.
