### ISSUE TITLE
Please help me, I'm obviously an indiot

### ISSUE THREAD

**Issue by MikeTheMike** [sveitser/kaggle_diabetic#6]
[RESOLVED} - I am an idiot! Forgot to convert the train_tiny set.....
Sorry for anyone who paid any attention to my madness!

I have been struggling for two weeks to get your code to run for a project for my degree.
I finally have it almost there. 
I'm using Ubuntu 14.04 have used virtualenv and managed to install requirements.txt manually one by one as for some reason i keep getting issues other ways. CUDNN backend is working and the code runs on the GPU.

edit: I couldn't install Shared Array 0.2 but can install 0.3? perhaps this is the issue?
edit: solved this but still having the same problem as described below.

When I try to run train_nn I get: 
Traceback (most recent call last):
  File "train_nn.py", line 40, in <module>
    main()
  File "/home/mike/.virtualenvs/test/local/lib/python2.7/site-packages/click/core.py", line 610, in **call**
    return self.main(_args, *_kwargs)
  File "/home/mike/.virtualenvs/test/local/lib/python2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/home/mike/.virtualenvs/test/local/lib/python2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/home/mike/.virtualenvs/test/local/lib/python2.7/site-packages/click/core.py", line 416, in invoke
    return callback(_args, **kwargs)
  File "train_nn.py", line 37, in main
    net.fit(files, labels)
  File "/home/mike/.virtualenvs/test/src/nolearn-master/nolearn/lasagne/base.py", line 334, in fit
    self.train_loop(X, y)
  File "/media/mike/Data/kaggleDR/nn.py", line 208, in train_loop
    X, y, self.eval_size)
  File "/media/mike/Data/kaggleDR/nn.py", line 118, in train_test_split
    X, y, test_size=eval_size)
  File "/media/mike/Data/kaggleDR/data.py", line 291, in split
    train, test = split_indices(files, labels, test_size, random_state)
  File "/media/mike/Data/kaggleDR/data.py", line 279, in split_indices
    labels = get_labels(names, per_patient=True)
  File "/media/mike/Data/kaggleDR/data.py", line 221, in get_labels
    return np.vstack([labels[left], labels[~left]]).T
IndexError: arrays used as indices must be of integer (or boolean) type

Please help me, I am desperate to understand this!

**Comment by MikeTheMike** [comment]
I am also getting these warnings before the Traceback:
/home/mike/.virtualenvs/test/src/lasagne-master/lasagne/init.py:86: UserWarning: The uniform initializer no longer uses Glorot et al.'s approach to determine the bounds, but defaults to the range (-0.01, 0.01) instead. Please use the new GlorotUniform initializer to get the old behavior. GlorotUniform is now the default for all layers.
  warnings.warn("The uniform initializer no longer uses Glorot et al.'s "
/media/mike/Data/kaggleDR/nn.py:146: UserWarning: lasagne.objectives.Objective is deprecated and will be removed for the first release of Lasagne. For alternatives, please see: http://lasagne.readthedocs.org/en/latest/modules/objectives.html
  obj = objective(output_layer, **objective_params)
/home/mike/.virtualenvs/test/src/lasagne-master/lasagne/layers/helper.py:69: UserWarning: get_all_layers() has been changed to return layers in topological order. The former implementation is still available as get_all_layers_old(), but will be removed before the first release of Lasagne. To ignore this warning, use `warnings.filterwarnings('ignore', '.*topo.*')`.
  warnings.warn("get_all_layers() has been changed to return layers in "
/home/mike/.virtualenvs/test/src/lasagne-master/lasagne/objectives.py:241: UserWarning: lasagne.objectives.mse() is deprecated and will be removed for the first release of Lasagne. Use lasagne.objectives.squared_error() instead.
  losses = self.loss_function(network_output, target)
couldn't load weights starting from scratch
fitting ...
